### ISSUE TITLE
HIS_12: Historial de reservas.

### ISSUE THREAD

**Issue by marrodoso** [ISPP-2021/Proyecto#15]
Permitir **ver** las **reservas** para un **usuario** determinado.

**Comment by rodgarcas** [comment]
REOPEN: _"Para la HIS-12 - Un método “Mis reservas” que me devuelva los bookings asociados a un usuario, junto con la información del servicio y el negocio asociados. Los links que están puestos no me hacen falta."_ (FrontEnd: Chus y Adri)
