### ISSUE TITLE
HIS_16: Detalles de perfil

### ISSUE THREAD

**Issue by rodgarcas** [ISPP-2021/Proyecto#16]
Permitir **ver** los **detalles** de un **usuario** en especifico.

**Comment by rodgarcas** [comment]
```
{
    "id": 1,
    "name": "Jose",
    "lastname": "Garcia",
    "dni": "00000000A",
    "email": "cosas@gmail.com",
    "bookings": [],
    "new": false,
    "_links": {
        "self": {
            "href": "http://localhost:8080/consumers/1"
        },
        "/consumers": {
            "href": "http://localhost:8080/consumers"
        }
    }
}
```

**Comment by antferdom** [comment]
El **contenido**, así como la resolución de esta historia de usuario, esta actualmente **contenido** a la hora de haber concluido  **HIS_17: Registro & procesamiento de usuarios**

**Detalles** : [HIS_17: Registro & procesamiento de usuarios](https://github.com/ISPP-2021/Proyecto/issues/34)
