### ISSUE TITLE
#001 Issue - Petición cambiar "Consumer" por "Costumer"

### ISSUE THREAD

**Issue by dansangar2** [ISPP-2021/Proyecto#17]
¿No sería apropiado cambiar la entidad "Consumer" por "Costumer", que sería "cliente"?
Creemos algunos de los miembros que "Cliente" sería un término más adecuado.

**Comment by antferdom** [comment]
A estas alturas no es algo ni esencial ni que genere mucho impacto positivo. Además de ser algo puramente conceptual.

**Comment by dansangar2** [comment]
Abrí esta ISSUE al principio del proyecto. Ya da igual, claro.

**Comment by dansangar2** [comment]
> A estas alturas no es algo ni esencial ni que genere mucho impacto positivo. Además de ser algo puramente conceptual.

Abrí esta ISSUE al principio del proyecto. Ya da igual, claro.
