### ISSUE TITLE
Revisión de la app y arreglo de problemas.

### ISSUE THREAD

**Issue by augmb** [ISPP-2021/Proyecto#53]
Realizar todos los casos de uso de la app y corregir errores. P. ej:
[] Cuando se registra un usuario, al logearse y entrar al perfil, no salen datos. Tampoco aparece su negocio o sus reservas.

**Comment by antferdom** [comment]
**Implementado** por parte del commit [c79a299ccb4d0731dabb5a55e14154963a85de1e].

**Comment by rodgarcas** [comment]
Arreglo de reservas pasada corregido en el commit aa70a11, al ser unos cambios mínimos se ha decidido subir directamente a la rama develop
